### ISSUE TITLE
mma新手，没有成功实现

### ISSUE THREAD

**Issue by zhuanqizhirou** [Moe-Net/Waifu-X#1]
![image](https://user-images.githubusercontent.com/4990547/81855354-d4ba5800-9591-11ea-9d16-46fc7e21aed4.png)
![image](https://user-images.githubusercontent.com/4990547/81855390-e26fdd80-9591-11ea-8282-253a31c9c598.png)

**Comment by oovm** [comment]
已经整合到 ResourceFunction["ImageSuperResolution"]

详见: https://resources.wolframcloud.com/FunctionRepository/resources/ImageSuperResolution

不要用这个了, 这个模型版本还是 11 时候的, 后来又多次大更新
